### ISSUE TITLE
Conda env create fails on Ubuntu16.04

### ISSUE THREAD

**Issue by zhouhao-learning** [MolecularAI/Reinvent#10]
Hello, I am very happy to see your work. I tried to reproduce your results, but I executed the `conda env create -f reinvent_shared.yml` command according to the environment installation method provided by you, but I got the following error:

```
Solving environment: failed

ResolvePackageNotFound: 
  - intel-openmp==2019.5=281

```

My computer system is Ubuntu 16.04, what is the problem and how should I solve it?

**Comment by patronov** [comment]
Hi, Thanks for reporting this. 
Its because I forgot to remove the builds from the *.yml
Just pushed the new version without the builds so the problem should not be present anymore.
