### ISSUE TITLE
What is the meaning of data processing

### ISSUE THREAD

**Issue by zhouhao-learning** [MolecularAI/Reinvent#13]
I’m looking at your data processing tutorial, but I don’t understand what this process is doing. I think many people who use REINVENT need to understand. Do you have data processing documentation and why do you want to process data like this?

**Comment by patronov** [comment]
Thanks for highlighting this. Will add some clarification to the notebook. 
To answer your question: there are two main reasons to clean up the training data. 

1. Get rid of unusual compounds that are clearly not drug-like (too big, reactive groups and etc.). There is normally no point training your model on such examples. And if you still need to reach some unorthodox location of  the chemical space your scoring function can take you there during the reinforcement learning.
2. There is a number of tokens that occur only for some instances. Again, these are rare compounds and can be seen as outliers. Excluding them frees a slot in the vocabulary and makes it smaller. Smaller vocabulary means faster training and less memory. As a result removing compounds that introduce rare tokens to the vocabulary speeds up your model.

There might be a good reason to include certain compounds and tokens that we have excluded and in that case you can re-run the notebook with your specific criteria.
However, the data used as an input in the current example is already purged so you cant see much difference between the input and the output. If I have the time I will re-run the notebook on some raw chembl input to show the clear contrast. Still, only a small portion of ChEMBL is actually removed.

Again, we appreciate the feedback so please, let us know if you find other parts of the tutorial unclear.
