### ISSUE TITLE
Could you please add more types of predictive property components?

### ISSUE THREAD

**Issue by JinChengneng** [MolecularAI/Reinvent#16]
Hi, I've found that the predictive property components of scoring are restricted to ```scikit-learn``` models only. However, there are different types of implemented predictive models in practice, such as ```PyTorch```. I wonder whether it's possible to add more supported types of predictive models such as ```PyTroch``` to ```Reinvent```.

**Comment by CMargreitter** [comment]
Hej again,
at the moment we don't have plans to support different interfaces. However, in the case of `PyTorch`, you might be able to 'wrap' it into the right `scikit-learn`-type of interface with [skorch](https://github.com/skorch-dev/skorch).

**Comment by JinChengneng** [comment]
Got it, I will look into ```skorch```. Thanks a lot. 
Just a kindly advice that maybe you can add this feature into the to-do list since lots of  QSAR models are not built with ```scikit-learn```.
