### ISSUE TITLE
Problem with RL molecular weight as scoring function component

### ISSUE THREAD

**Issue by Gromax13** [MolecularAI/Reinvent#18]
Hi,
I'm trying to use Molecular weight as a scoring function component using this .py script to create the .json to submit:

        # load dependencies
    import os
    import re
    import json
    import tempfile

    # --------- change these path variables as required
    reinvent_dir = os.getenv('REINVENT_DIR')
    #module load 
    #reinvent_env = os.path.expanduser("")
    output_dir = os.path.expanduser("/home/s970675/reinvent_test/test_soglie/MW")

    # --------- do not change
    #get the notebook's root path
    #try: ipynb_path
    #except NameError: ipynb_path = os.getcwd()

    # if required, generate a folder to store the results
    try:
        os.mkdir(output_dir)
    except FileExistsError:
        pass

    # initialize the dictionary
    configuration = {
        "version": 2,                          # we are going to use REINVENT's newest release
        "run_type": "reinforcement_learning"   # other run types: "sampling", "validation",
                                            #                  "transfer_learning",
                                            #                  "scoring" and "create_model"
    }
    # add block to specify whether to run locally or not and
    # where to store the results and logging
    configuration["logging"] = {
        "sender": "http://127.0.0.1",          # only relevant if "recipient" is set to "remote"
        "recipient": "local",                  # either to local logging or use a remote REST-interface
        "logging_frequency": 10,               # log every x-th steps
        "logging_path": os.path.join(output_dir, "progress.log"), # load this folder in tensorboard
        "resultdir": os.path.join(output_dir, "results"),         # will hold the compounds (SMILES) and summaries
        "job_name": "Reinforcement learning demo",                # set an arbitrary job name for identification
        "job_id": "demo"                       # only relevant if "recipient" is set to "remote"
    }
    # add the "parameters" block
    configuration["parameters"] = {}

    # add a "diversity_filter"
    configuration["parameters"]["diversity_filter"] =  {
        "name": "IdenticalMurckoScaffold",     # other options are: "IdenticalTopologicalScaffold", 
                                            #                    "NoFilter" and "ScaffoldSimilarity"
                                            # -> use "NoFilter" to disable this feature
        "nbmax": 25,                           # the bin size; penalization will start once this is exceeded
        "minscore": 0.4,                       # the minimum total score to be considered for binning
        "minsimilarity": 0.4                   # the minimum similarity to be placed into the same bin
    }

    # prepare the inception (we do not use it in this example, so "smiles" is an empty list)
    configuration["parameters"]["inception"] = {
        "smiles": [],                          # fill in a list of SMILES here that can be used (or leave empty)
        "memory_size": 100,                    # sets how many molecules are to be remembered
        "sample_size": 10                      # how many are to be sampled each epoch from the memory
    }

    # set all "reinforcement learning"-specific run parameters
    configuration["parameters"]["reinforcement_learning"] = {
        "prior": os.path.join(reinvent_dir, "data/augmented.prior"), # path to the pre-trained model
        "agent": os.path.join(reinvent_dir, "data/augmented.prior"), # path to the pre-trained model
        "n_steps": 125,                        # the number of epochs (steps) to be performed; often 1000
        "sigma": 128,                          # used to calculate the "augmented likelihood", see publication
        "learning_rate": 0.0001,               # sets how strongly the agent is influenced by each epoch
        "batch_size": 128,                     # specifies how many molecules are generated per epoch
        "reset": 0,                            # if not '0', the reset the agent if threshold reached to get
                                            # more diverse solutions
        "reset_score_cutoff": 0.5,             # if resetting is enabled, this is the threshold
        "margin_threshold": 50                 # specify the (positive) margin between agent and prior
    }

    component_molecular_weight = {
        "component_type": "mol_weight",
        "name": "Molecular Weight",    # arbitrary name for the component
        "weight": 1,                           # the weight of the component (default: 1)
        "model_path": None,                    # not required; note, this is "null" in JSON
        "smiles": [],                          # not required
        "specific_parameters": {
            "transformation_type": "step",
            "high": 650,
            "low": 300,
            "transformation": True
            }      
    }

    scoring_function = {
        "name": "custom_product",              # this is our default one (alternative: "custom_sum")
        "parallel": False,                     # sets whether components are to be executed
                                            # in parallel; note, that python uses "False" / "True"
                                            # but the JSON "false" / "true"

        # the "parameters" list holds the individual components
        "parameters": [
            component_molecular_weight
        ]
    }

    configuration["parameters"]["scoring_function"] = scoring_function
    # write the configuration file to the disc
    configuration_JSON_path = os.path.join(output_dir, "RL_config.json")
    with open(configuration_JSON_path, 'w') as f:
        json.dump(configuration, f, indent=4, sort_keys=True)

However when I try to run REINVENT i get this error:
'''
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint8 = np.dtype([("qint8", np.int8, 1)])
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint16 = np.dtype([("qint16", np.int16, 1)])
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint32 = np.dtype([("qint32", np.int32, 1)])
    /progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])
    Traceback (most recent call last):
    File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/input.py", line 25, in <module>
        main()
    File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/input.py", line 21, in main
        manager.run()
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/manager.py", line 95, in run
        job()
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/manager.py", line 46, in _run_reinforcement_learning
        scoring_function = self._setup_scoring_function(rl_components.scoring_function)
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/manager.py", line 62, in _setup_scoring_function
        scoring_function_instance = ScoringFunctionFactory(scoring_function_parameters)
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/scoring_function_factory.py", line 16, in __new__
        return cls.create_scoring_function_instance(sf_parameters, scoring_function_registry)
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/scoring_function_factory.py", line 25, in create_scoring_function_instance
        return scoring_function(parameters, sf_parameters.parallel)
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/function/custom_product.py", line 14, in __init__
        super().__init__(parameters, parallel)
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/function/base_scoring_function.py", line 39, in __init__
        self.scoring_components = factory.create_score_components()
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/score_components/score_component_factory.py", line 39, in create_score_components
        return [self._current_components.get(p.component_type)(p) for p in self._parameters]
    File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/scoring/score_components/score_component_factory.py", line 39, in <listcomp>
        return [self._current_components.get(p.component_type)(p) for p in self._parameters]
    TypeError: 'NoneType' object is not callable
'''
I tried with other phys-chem properties everything runs smoothly, I'm wondering if this is a problem of MW component..
Thanks in advance for your help.

**Comment by patronov** [comment]
Hi, Thanks for using REINVENT.

You have identified correctly the problem. 
The actual value for this component type is: "molecular_weight" not "mol_weight". You can find the full list of supported component types [here](https://github.com/MolecularAI/Reinvent/blob/9c57636f9d32b4ce5b75670f43906a70d5daf886/utils/enums/scoring_function_component_enum.py#L130)

Let us know if you have any other issues.

**Comment by Gromax13** [comment]
Hi, 
thanks very much for your help!

Cheers
