### ISSUE TITLE
Reorganize repository as python package

### ISSUE THREAD

**Issue by cthoyt** [MolecularAI/Reinvent#2]
Hi, it would be nice to be able to pip install this code.

I would be happy to help with a PR or give advice if you're not sure how to do this.

**Comment by CMargreitter** [comment]
Hej,

currently, that's not on our agenda but it's worth a thought for future reference.
Will keep this one open until we have brought the repo to a solid state.

Absolutely, we'd appreciate any help you can provide :)

**Comment by cthoyt** [comment]
Great! Will do, but I think first to keep us all out of possible legal trouble from AZ check out #4

**Comment by cthoyt** [comment]
Would you be able to improve the documentation so I could actually test using the package? Right now i can reorganize the code fine, but without having a sanity check, it's just going to be a diff with 100's of changed files. Plus I will need to help rewrite documentation for how to use this code after it's packaged, which is a bit different than just running python scripts and hoping to god all the imports are right
