### ISSUE TITLE
Test error and type error

### ISSUE THREAD

**Issue by ErikZhang-9762** [MolecularAI/Reinvent#21]
Hi，
Thank you for developing such an excellent tool!
I had some problems when I ran the code.
The first is type error when I run transfer_ learning tutorial, 
Typeerror appears: 'Nonetype' object is not callable.I was confused.
The error report is as follows：
Exception ignored in: <function LocalTransferLearningLogger.__del__ at 0x7f04ecea2830>
Traceback (most recent call last):
  File "/home/ubuntu-61/code/Reinvent-1-master/Reinvent-1-master/running_modes/transfer_learning/logging/local_transfer_learning_logger.py", line 21, in __del__
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 1033, in close
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 133, in flush
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 106, in flush
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 155, in flush
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/queue.py", line 89, in join
  File "/home/ubuntu-61/anaconda3/envs/pytorch4/lib/python3.7/threading.py", line 289, in wait
TypeError: 'NoneType' object is not callable

The second error is assertion error，

When I run“python -m pytest unittest_reinvent”,report 4 failed, 92 passed, 29 warnings.
The error report is as follows：
======================== FAILURES ===============================================================
______________________________________ Test_model_functions.test_likelihood_function_differences _______________________________________

self = <unittest_reinvent.model_function_tests.test_model_functions.Test_model_functions testMethod=test_likelihood_function_differences>

    def test_likelihood_function_differences(self):
        seq, sample, nll = self.model.sample_sequences_and_smiles(batch_size=128)
        nll2 = self.model.likelihood(seq)
        nll3 = self.model.likelihood_smiles(sample)
>       nt.assert_array_almost_equal(nll.detach().cpu().numpy(), nll2.detach().cpu().numpy(), 3)
E       AssertionError: 
E       Arrays are not almost equal to 3 decimals
E       
E       Mismatch: 45.3%
E       Max absolute difference: 0.00488281
E       Max relative difference: 0.00026931
E        x: array([19.316, 28.097, 33.41 , 18.136, 45.46 , 24.451, 43.118, 38.982,
E              32.112, 20.839, 21.984, 32.963, 21.883, 30.506, 37.408, 31.448,
E              24.063, 43.964, 38.294, 21.17 , 42.545, 34.434, 27.453, 27.187,...
E        y: array([19.313, 28.096, 33.409, 18.131, 45.459, 24.447, 43.119, 38.986,
E              32.115, 20.837, 21.984, 32.965, 21.884, 30.507, 37.411, 31.451,
E              24.063, 43.965, 38.294, 21.171, 42.546, 34.435, 27.452, 27.185,...

unittest_reinvent/model_function_tests/test_model_functions.py:65: AssertionError
__________________________________________ Test_model_functions.test_likelihoods_from_model_1 __________________________________________

self = <unittest_reinvent.model_function_tests.test_model_functions.Test_model_functions testMethod=test_likelihoods_from_model_1>

    def test_likelihoods_from_model_1(self):
        likelihoods = self.model.likelihood_smiles(["CCC", "c1ccccc1"])
>       self.assertAlmostEqual(likelihoods[0].item(), 20.9116, 3)
E       AssertionError: 20.9108943939209 != 20.9116 within 3 places (0.0007056060791015284 difference)

unittest_reinvent/model_function_tests/test_model_functions.py:28: AssertionError
_____________________________________________ Test_murcko_scaffold_filter.test_save_to_csv _____________________________________________

self = <unittest_reinvent.scaffoldfilter_tests.test_murcko_scaffold_filter.Test_murcko_scaffold_filter testMethod=test_save_to_csv>

    def test_save_to_csv(self):
        folder = self.workfolders[0]
        self.scaffold_filter.save_to_csv(folder)
        output_file = os.path.join(folder, "scaffold_memory.csv")
>       self.assertEqual(os.path.isfile(output_file), True)
E       AssertionError: False != True

unittest_reinvent/scaffoldfilter_tests/test_murcko_scaffold_filter.py:56: AssertionError
_______________________________________________ Test_no_scaffold_filter.test_save_to_csv _______________________________________________

self = <unittest_reinvent.scaffoldfilter_tests.test_no_filter.Test_no_scaffold_filter testMethod=test_save_to_csv>

    def test_save_to_csv(self):
        folder = self.workfolders[0]
        self.scaffold_filter.save_to_csv(folder)
        output_file = os.path.join(folder, "scaffold_memory.csv")
>       self.assertEqual(os.path.isfile(output_file), True)
E       AssertionError: False != True

unittest_reinvent/scaffoldfilter_tests/test_no_filter.py:53: AssertionError
my running platform ： linux -- Python 3.7.8, pytest-5.3.0, py-1.9.0, pluggy-0.13.1
I don't know if this is related to the error above. 

Thanks in advance for your help,

Sincerely

**Comment by patronov** [comment]
Thanks for using Reinvent!
The **first error** suggests an issue with the configuration and specifically with the logging path parameter. I would suggest to check for a missing value in the input.json. You could also attach it and we can have a look.

Regarding the **second error** best use: 

> python main_test.py

I should remove the other options as they are artefacts from the repo we have internally.

Hope this helps.

**Comment by ErikZhang-9762** [comment]
Hi，
First of all, thank you for your guidance
I checked the JSON file, but I found nothing wrong.
I attached the JSON file at the back,
I hope you can point out the mistakes for me
I really appreciate your generous help.
[json.zip](https://github.com/MolecularAI/Reinvent/files/5611757/json.zip)

**Comment by jiaxi-zhao** [comment]
Hi!
I have used your input.json and only changed path and num_epochs, it worked for me. The first error suggests that in local_transfer_learning_logger.py
https://github.com/MolecularAI/Reinvent/blob/master/running_modes/transfer_learning/logging/local_transfer_learning_logger.py
del method line 21 tensorboard hasn't been instantiated. Think there might be an issue with tensorboard, you can check if tensorboard is installed in the environment.
Here is the input.json I am using.
[json.zip](https://github.com/MolecularAI/Reinvent/files/5635799/json.zip)
Hope this helps.

**Comment by JXZhaocc** [comment]
Hi!
I have used your input.json and only changed path and num_epochs, it worked for me. The first error suggests that in local_transfer_learning_logger.py
https://github.com/MolecularAI/Reinvent/blob/master/running_modes/transfer_learning/logging/local_transfer_learning_logger.py
del method line 21 tensorboard hasn't been instantiated. Think there might be an issue with tensorboard, you can check if tensorboard is installed in the environment.
Here is the input.json I am using.
[json.zip](https://github.com/MolecularAI/Reinvent/files/5635871/json.zip)
Hope this helps.

**Comment by ErikZhang-9762** [comment]
Hi，
I checked my tensorboard before,
I'm sure I have tensorboard installed in the CONDA environment
I used tensorboard 1.15.0 (rtx3080 support)
I solved the error in another way, but I don't know if it will affect the result
the error line21 is self._summary_writer.close()
I removed the brackets and the error disappeared.
now the line 21 is self._summary_writer.close   And the code runs

I'm a student in drug design. 
I've noticed that reinvent can make some functional improvements. 
If you need it, I'd like to help you improve it.

Thanks for your help！
