### ISSUE TITLE
KeyError: '%10' when train a new model 

### ISSUE THREAD

**Issue by ErikZhang-9762** [MolecularAI/Reinvent#22]
Hi,

Thank you for your code！Again！
When I was training a new model, I encountered some mistakes，
I used methods from reinventcommunity to standardize smi files，
But the problem is not solved
When I trained to the fourth epoch, the problem occurred，KeyError: '%10' 
The smi file  is attached.(a txt file)

Thanks in advance for your help,

Sincerely
[2.filtered.zip](https://github.com/MolecularAI/Reinvent/files/5688974/2.filtered.zip)

**Comment by ErikZhang-9762** [comment]
Rewrite. SMI file solves this problem.

**Comment by Gromax13** [comment]
Hi,

I have the same problem that you described: could you please comment a bit more on how you solved it?

Thanks in advance,

Cheers

**Comment by ErikZhang-9762** [comment]
Hi，@Gromax13

Use the methods in ReinventCommunity to process the dataset before building a new model.

For details please refer to：
https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Data_Preparation.ipynb

The empty model was also built using this cleaned dataset.
Do not use the empty model from before.

Hope this is helpful to you.
