### ISSUE TITLE
How to get the batches of the generated compounds? 

### ISSUE THREAD

**Issue by recherHE** [MolecularAI/Reinvent#24]
Theoretically,for generative model,the Batches of compounds generated early would be Unwanted,so I try to get The last few batches of compounds and Loop multiple times with some change in configuration.After checking the results file,I found there was
no batches related information.
Of course, because the scores are an overall upward trend, dividing them according to scores is also a desirable way.But I still want to know if there is a way to get batch information.

look forward to hearing from you if it doesn't bother you. thx~

**Comment by patronov** [comment]
Currently, there is no information about the batch/step number logged out.
However, we are preparing to release a new version where this is available. It should be ready within the next couple of weeks. It will be added as a separate branch.

**Comment by recherHE** [comment]
thanks for your remind!,looking forward for the new release.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 29, 2021 22:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MolecularAI/Reinvent] How to get the batches of the generated compounds?  (#24)




 
Currently, there is no information about the batch/step number logged out.
 However, we are preparing to release a new version where this is available. It should be ready within the next couple of weeks. It will be added as a separate branch.
