### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by MiloszGrabski** [MolecularAI/Reinvent#28]
Hi,
Creating environment does not work (Windows10):

..\Reinvent>conda env create -f reinvent.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libedit=3.1.20181209
  - ld_impl_linux-64=2.33.1
  - libgcc-ng=9.1.0
  - glib=2.63.1
  - gstreamer=1.14.0
  - libgfortran-ng=7.3.0
  - ncurses=6.2
  - secretstorage=3.2.0
  - dbus=1.13.12
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - gst-plugins-base=1.14.0
  - readline=8.0

Thanks

**Comment by patronov** [comment]
The current implementation is not intended to run on Windows. It has been only tested and used on Linux. Therefore the dependencies in the *.yml file are explicitly looking for Linux packages.

**Comment by MiloszGrabski** [comment]
ok, thanks for the update.
