### ISSUE TITLE
python main_test.py failed 

### ISSUE THREAD

**Issue by xuzhang5788** [MolecularAI/Reinvent#29]
Thank you so much for your great repo.
I followed the instruction and created a conda environment and run
python main_test.py
I got the following error messages:

(reinvent.v3.0) xzhang@R1124G1:~/projects/Reinvent$ python main_test.py 
Traceback (most recent call last):
  File "main_test.py", line 7, in <module>
    from unittest_reinvent.running_modes import *
  File "/home/xzhang/projects/Reinvent/unittest_reinvent/running_modes/__init__.py", line 1, in <module>
    from unittest_reinvent.running_modes.create_model_tests import *
  File "/home/xzhang/projects/Reinvent/unittest_reinvent/running_modes/create_model_tests/__init__.py", line 1, in <module>
    from unittest_reinvent.running_modes.create_model_tests.test_create_model import TestCreateModel
  File "/home/xzhang/projects/Reinvent/unittest_reinvent/running_modes/create_model_tests/test_create_model.py", line 9, in <module>
    from unittest_reinvent.fixtures.paths import MAIN_TEST_PATH, SMILES_SET_PATH
  File "/home/xzhang/projects/Reinvent/unittest_reinvent/fixtures/paths.py", line 5, in <module>
    with open(os.path.join(project_root, '../../configs/config.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhang/projects/Reinvent/unittest_reinvent/fixtures/../../configs/config.json'

Could you please help me? Thanks

**Comment by patronov** [comment]
Thanks for your interest in REINVENT.
To use the unit tests you need to create config.json file with setting certain paths. This is also described in the readme.
SMILES_SET_PATH should be the file located in : [Reinvent Community](https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/data/smiles.smi)
Please, let us know if that is not the case.

**Comment by xuzhang5788** [comment]
Thank you for your reply. 
Do you mean that based on config/example.config.json, create a config.json file? But I don't have OpenEye license, could you tell me how to modify the example.config.json. Many thanks!

**Comment by patronov** [comment]
@xuzhang5788  I would only assign a path to the `"MAIN_TEST_PATH"` variable. Simply copy the rest of the contents of the example into the `config/config.json`

@GuoJeff I suspect we would need to think of some more intuitive example of how to set up the `config/config.json` file. This seems to confuse a lot of people.
