### ISSUE TITLE
Complete Use Case in Reinvent Community

### ISSUE THREAD

**Issue by dd1github** [MolecularAI/Reinvent#33]
Hi, the Complete Use Case example appears to be missing the drd2.pkl file.  When I used the old drd2.pkl file (from a download from a few days ago), the file raised an error, ModuleNotFoundError: No module named 'sklearn.ensemble.forest'.  I believe this is because sklearn changed the name of this model to sklearn.ensemble._forest.  Can you please provide an updated drd2.pkl file that works with the Use Case Example?  Thanks.

**Comment by patronov** [comment]
Hi, thanks for reporting this. The file has been moved to:
https://github.com/MolecularAI/ReinventCommunity/tree/master/notebooks/models
@GuoJeff  could you please update this example:
https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Complete_Use-Case-DRD2_Demo.ipynb
it points to `/data/drd2.pkl` instead of pointing to `/models/drd2.pkl`

**Comment by GuoJeff** [comment]
Hi @dd1github,

I have changed the path and re-uploaded the previously corrupt drd2.pkl model.

**Comment by dd1github** [comment]
Thanks, but this still does not work.

It still returns the same error

Exception: The loaded file .../drd2.pkl isn't a valid scikit-learn model

I believe that the drd2 file was created in an old version of scikit learn
and therefore does not work.


Best,
Damien

**Comment by patronov** [comment]
Which version of scikit are you using?
Is it scikit-learn=0.21.3 ?

**Comment by dd1github** [comment]
I am using 0.24.2


Best,
Damien

**Comment by patronov** [comment]
Current models are compatible with up to 0.21.3
They wont work with newer versions.

In the future we will aim to become compatible with the recently released v 1.0 of scikit-learn but this may require to adapt to potential changes of the interface. Havent had the chance to review it yet.

Best,

Atanas
