### ISSUE TITLE
Does Reinvent implement reaction rules?

### ISSUE THREAD

**Issue by JuanLuGMid** [MolecularAI/Reinvent#38]
Thanks a lot for this amazing tool! I wonder if Reinvent is implementing any kind of reaction rules for its computations. For instance, other tools such as RetroPath include them. If reaction rules are not considered, how reinvent determines if a SMILE is valid or not?

Thank in advance :)

**Comment by JuanLuGMid** [comment]
> _No description provided._

Thanks a lot for this amazing tool! I wonder if Reinvent is implementing any kind of reaction rules for its computations. For instance, other tools such as RetroPath include them. If reaction rules are not considered, how reinvent determines if a SMILE is valid or not?

Thank in advance :)

**Comment by patronov** [comment]
Thanks for the positive feedback!
Reinvent doesnt implement reaction rules in its standard modes. The SMILES are simply evaluated as valid if they can be correctly transformed into valid molecules by RDKit. 
Currently, LibINVENT is integrated with REINVENT and we have a bunch of examples [here](https://github.com/MolecularAI/ReinventCommunity/tree/master/notebooks) . In LibINVENT you can define explicit attachment points on a scaffold, you can compose a set of scoring objectives, and then you can also define reactions by which these attachment points should be extended. This is particularly useful for library design scenarios where all compounds can be synthesized by the same type of reactions.
