### ISSUE TITLE
What's the different between REINVENT 2.0 and 3.x?

### ISSUE THREAD

**Issue by charlesxu90** [MolecularAI/Reinvent#39]
Hello,

I saw REINVENT 3.0 is under active development. What's the different between 3.x and 2.0/2.1? Which should we use for an academic study?

**Comment by GuoJeff** [comment]
Hi @charlesxu90,

REINVENT 3.0 is the latest major version with many additional functionalities compared to 2.0, including running modes such as LibINVENT and Automated Curriculum Learning. There are also many configuration JSON changes in the 3.0 version.

In the REINVENT README, the current version is denoted 3.1. Going forward, updates will increment 3.2, 3.3, etc. until a new major release is required. Therefore, REINVENT 3.0 should be used.

**Comment by charlesxu90** [comment]
Get it. Thanks for answering.

**Comment by j3mdamas** [comment]
Furthermore, Reinvent 3.x also allows dockstream scoring component (https://github.com/MolecularAI/DockStream). Closing.
