### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by cthoyt** [MolecularAI/Reinvent#4]
technically without a license, nobody else can use this code. It would be good to add one. If you're not familiar with licensing, this site is helpful: https://choosealicense.com/. The best ones for academic work IMO are MIT and Apache

**Comment by CMargreitter** [comment]
Y, very true. Added a LICENSE now, thanks for bringing it up.

**Comment by C-nit** [comment]
@CMargreitter @patronov Where do I find the licence?

**Comment by j3mdamas** [comment]
I see it got deleted on 982b26dd6cfeb8aa84b6d7e4a8c2a7edde2bad36, but I assume it's still MIT license.

**Comment by patronov** [comment]
I just added the license. Actually with version 3.0 we are switching to Apache 2 hope this is not an obstacle.
