### ISSUE TITLE
Suggestion: Torch.cuda.is_available() checks for Reinvent Models PyPI Package

### ISSUE THREAD

**Issue by Ashish13898** [MolecularAI/Reinvent#41]
PyPI Package : [Reinvent Models](https://pypi.org/project/reinvent-models/0.0.14/)
Version : 0.0.14
Suggestion :  Additional CUDA checks to make the package compatible with cpu

Hello everyone,

Firstly, allow me thank you building this amazing library, we are building an [open source library](https://github.com/GT4SD/gt4sd-core) to accelerate hypothesis generation in the scientific discovery process where we have integrated, among others, reinvent-models to allow users to generate molecules using your framework.

We have noticed that the package reinvent-models is missing CUDA checks in some parts of the code base where is assuming that it'll always run on gpu.

To overcome this limitation, we mirrored in a [repo](https://github.com/GT4SD/reinvent_models) the PyPI package of the latest version of reinvent-models and add those changes to make it compatible with cpu.

Since we thought this might be a useful change, we thought you could consider including this in the next release of the package.

Please let us know your thoughts on this and thanks again for the amazing work :)

Kind regards,
Ashish Dave

**Comment by halx** [comment]
Sorry for the very late reply but I have taken over the project just recently.

Many thanks for you efforts.  Unfortunately, getting pytorch to work correctly with GPU costs a bit of extra effort.  However, we are currently work to ensure that the software runs on CPUs just as well.

**Comment by j3mdamas** [comment]
@halx I think that's why they have contributed [a PR](https://github.com/MolecularAI/reinvent-models/pull/1), so that the work can be incorporated back into reinvent-models. Please correct me if I'm wrong, @Ashish13898 or @drugilsberg.

**Comment by drugilsberg** [comment]
No worries @halx. Actually @j3mdamas is correct. The proposed changed ensure that inference on CPU would run smoothly and with no issues.

**Comment by halx** [comment]
Many thanks for the answers.  The current code has changed so much that changes in any PR would have to be incorporated by hand.  Also, the suggested code change is no good because it will run on the GPU automatically when it is detected.  What is needed is an explicit control by the user where to run.  This would also enable proper testing which that code wouldn't allow me to do.  We have been working on this and we think we have found a satisfactory solution.  We plan to release this to the public this year.
