### ISSUE TITLE
Tracing docking results from Dockstream

### ISSUE THREAD

**Issue by LarsAC** [MolecularAI/Reinvent#43]
Hello,

it seems a bit tedious to go from Reinvent results, that include Dockstream in its objective function, to the docked poses of molecules in the SDF files that Dockstream has written during its runs. Essentially I need to look up the step in Reinvent, open the correct SDF file for the step in which the molecule was generated, identify the molecule via its SMILES string and then I know which docking pose I can inspect in the SDF file.

Can you share some ideas how you work with this in practice ? Is there some option to configure better lineage, e.g. achieve consistent ligand names in Dockstream and reinvent output ?

Lars

**Comment by GuoJeff** [comment]
Hi @LarsAC,

At the moment, there is no built-in method to extract individual SDF coordinates from the DockStream output. This would likely depend on what specific SMILES you are interested in extracting, for example, those that achieve a docking score below a certain threshold. In practice, I use a script to extract the poses I want (based on certain criteria or top X% in the scaffold memory) from the parent folder containing all the output SDF files.

**Comment by LarsAC** [comment]
Hi @GuoJeff ,

thanks for the explanation. I understand how you approach the problem and thought about this myself. Is there a simple way to deal with stereo isomers ? Or do you filter lowest conformers from dockstream csv and map via standardized smiles back to the Reinvent results ?

Lars

**Comment by GuoJeff** [comment]
Hi @LarsAC,

If you enumerate stereoisomers in the "ligand preparation" step of DockStream, then all stereoisomers that are sent to the docking step will receive a score. However, only the best docking conformer will be fed back into REINVENT and the DockStream example configuration JSON in the DockStreamCommunity repo is set-up such that only the best scoring stereoisomer is written out (SDF + docking score CSV). 

In case of extracting this score, something I have done before is simply match the docking score from the scaffold memory to the SDF file. If using Glide, the number of significant digits in the docking score is sufficient for 1 match to be found. I recall that you were using AutoDock Vina which in the DockStream implementation only outputs docking scores to 1 decimal place. Matching scores might lead to multiple matches so instead, I would probably canonicalize the SMILES in the scaffold memory and use that to match the canonicalized SMILES in the SDF.

**Comment by LarsAC** [comment]
Hi @GuoJeff,

thanks for the additional explanations, that makes sense.
