### ISSUE TITLE
Reinvent 3.2 version inconsistencies

### ISSUE THREAD

**Issue by j3mdamas** [MolecularAI/Reinvent#45]
Hi,

I was trying to install Reinvent 3.2 and while deciding from which commit/tag to install from, I identified some inconsistencies.

Looking at the commit graph (https://github.com/MolecularAI/Reinvent/network), I see that there is a source code drift between master and the reinvent3.2 branch. Namely, there are two commits that seem to be associated with most of the 3.2 update, but they are different commits in each branch: https://github.com/MolecularAI/Reinvent/commit/8abbb0c30427b364143f383b5b2e0ea9756634c5#diff-f05597e59d240c2c8e8430d508288b0bbaacaddf679e467815fb6c7c3110ac43 and https://github.com/MolecularAI/Reinvent/commit/b7324d222a49d18b08335a01649abdb0ac66a734#diff-f05597e59d240c2c8e8430d508288b0bbaacaddf679e467815fb6c7c3110ac43

I cloned and diffed the commits directly, and there are many differences. For the installation, most notably:
```
-    - reinvent-models==0.0.15rc1
+    - reinvent-models==0.0.25
```
Since PyPi doesn't have the 0.0.25 version available, I had no choice but to consider b7324d2 as version 3.2, but it would be good to clarify this point to make sure the source code is consistent and correct.

tagging @GuoJeff since you made most of these commits.

Thanks,
João

**Comment by jiazhenhe** [comment]
Hi @j3mdamas, thanks for raising this up. Now the master and reinvent.3.2 branch are consistent.

**Comment by j3mdamas** [comment]
Thanks! I'll install soon from the release and close after I tested it.

**Comment by j3mdamas** [comment]
It is solved, thanks!
