### ISSUE TITLE
How do you write your name?

### ISSUE THREAD

**Issue by jonalv** [MolecularAI/Reinvent#46]
Hi, I am wondering how you prefer to write the name of your project. So far I ahve seen the following alternatives at various locations:

- REINVENT
- Reinvent
- [RE]-Invent

Which one is preferred?

Thanks!

**Comment by halx** [comment]
Sorry for the very late reply but I have taken over the project just recently.

I think there is no preferred way to spell the name,  For publications we have used the all uppercase variant which is meant to refer to the complete software system.  But we also use "Reinvent" (internally) to refer to the original de-novo algorithm.  Frankly, the naming hasn't really been worked out.
