### ISSUE TITLE
How to run Reinveint in parallel?

### ISSUE THREAD

**Issue by hqi77** [MolecularAI/Reinvent#48]
Hi,

Firstly, thank you for the developing these excellent resources. 

I wonder, would it be possible to run Reinvent on multiple CPUs or GPUs in parallel? 

Thank you for your time

**Comment by halx** [comment]
Sorry for the very late reply but I have taken over the project just recently.

REINVENT does currently not support multiple GPUs.  I believe pytorch can use multiple CPU/cores and this can be controlled via certain environment variables.
