### ISSUE TITLE
I tried to follow the steps to install Reinvent, but can't create the environment, it shows "ResolvePackageNotFound:"

### ISSUE THREAD

**Issue by manajit-das** [MolecularAI/Reinvent#49]
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ld_impl_linux-64=2.33.1
  - secretstorage=3.2.0
  - libgcc-ng=9.1.0
  - gstreamer=1.14.0
  - libedit=3.1.20181209
  - libuuid=1.0.3
  - ncurses=6.2
  - glib=2.63.1
  - libstdcxx-ng=9.1.0
  - libgfortran-ng=7.3.0
  - gst-plugins-base=1.14.0
  - readline=8.0
  - dbus=1.13.12

**I followed some suggestion from here, https://github.com/datitran/object_detector_app/issues/41
But, it resulted in "Found conflicts! Looking for incompatible packages."
Thanks for your help.**

**Comment by halx** [comment]
I am very sorry for the very late reply but I have taken over the project just recently.

Were you able to resolve this issue? What where the steps to install the software?  I would need more details to fix this.
