### ISSUE TITLE
Use of individual config filenames prevented

### ISSUE THREAD

**Issue by pmaen** [MolecularAI/Reinvent#50]
One line in the `input.py` prevents `Reinvent`to use config files in different directories and with different file names, which among other things makes tutorials like this one (https://github.com/MolecularAI/ReinventCommunity/blob/d9fa00faaccb5bf40913d21250aac1dde52cdad7/notebooks/Complete_Use-Case-DRD2_Demo.ipynb) impossible without changing the code by hand.
https://github.com/MolecularAI/Reinvent/blob/b7324d222a49d18b08335a01649abdb0ac66a734/input.py#L11

**Comment by halx** [comment]
Sorry for the very late reply but I have taken over the project just recently.

Yes, you are right.  We are currently reworking in how REINVENT will work in the future so we will also fix this.
