### ISSUE TITLE
What's the version of ChEMBL dataset for training the prior generative model?

### ISSUE THREAD

**Issue by xuelianl** [MolecularAI/Reinvent#51]
Hello, 
    I would like to know what's the version of ChEMBL dataset used for training the prior generative model?
Thanks,
xuelianl

**Comment by halx** [comment]
Hi xuelianl,

many thanks for your interest in REINVENT.

I can refer you to the relevant literature:
LibINVENT used ChEMBL27, see https://doi.org/10.1021/acs.jcim.1c00469
Link-INVENT used ChEMBL27, see https://doi.org/10.1039/D2DD00115B
The original REINVENT paper cites the ChEMBL paper from 2017, see https://doi.org/10.1186/s13321-019-0393-0

Many thanks,
Hannes.
