### ISSUE TITLE
unittest failure

### ISSUE THREAD

**Issue by PatWalters** [MolecularAI/Reinvent#8]
I'm getting a failure when I do "python -m unittest"

```
======================================================================
FAIL: test_inception_model_1 (unittest_reinvent.inception_tests.test_add.Test_inception_model_add)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/software/Reinvent/unittest_reinvent/inception_tests/test_add.py", line 50, in test_inception_model_1
    self.assertEqual(len(self.inception_model.memory), 3)
AssertionError: 4 != 3
```

Any suggestions?

**Comment by patronov** [comment]
Thanks for spotting this. I updated the README. 
Best use "python main_test.py". 
"python -m unittest" apparently executes the tests in a different order and this particular test relies on persisting the state of the test class "setUpClass" which in turn results in a failing test.
